// <auto-generated />
using System;
using AcademiaIMC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcademiaIMC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221208221806_imc")]
    partial class imc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("AcademiaIMC.Models.IMC", b =>
                {
                    b.Property<int>("IMCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("resultado")
                        .HasColumnType("REAL");

                    b.HasKey("IMCId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Imcs");
                });

            modelBuilder.Entity("AcademiaIMC.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AcademiaIMC.Models.IMC", b =>
                {
                    b.HasOne("AcademiaIMC.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
